remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Wonkam Lab
description: Genetic Medicine and African Populations

github:
  is_project_page: true
